NAMES = """EMPTY ANNOTATION IDENTIFIER LITERAL
LESS LESS_EQUAL GREATER GREATER_EQUAL EQUAL_EQUAL BANG_EQUAL
AND OR NOT AMPERSAND_AMPERSAND PIPE_PIPE BANG
AMPERSAND PIPE TILDE CARET LESS_LESS GREATER_GREATER
PLUS MINUS STAR STAR_STAR SLASH PERCENT
EQUAL PLUS_EQUAL MINUS_EQUAL STAR_EQUAL STAR_STAR_EQUAL SLASH_EQUAL PERCENT_EQUAL
LESS_LESS_EQUAL GREATER_GREATER_EQUAL AMPERSAND_EQUAL PIPE_EQUAL CARET_EQUAL
IF ELIF ELSE FOR WHILE BREAK CONTINUE PASS RETURN MATCH WHEN
AS ASSERT AWAIT BREAKPOINT CLASS CLASS_NAME CONST ENUM EXTENDS FUNC IN IS
NAMESPACE PRELOAD SELF SIGNAL STATIC SUPER TRAIT VAR VOID YIELD
BRACKET_OPEN BRACKET_CLOSE BRACE_OPEN BRACE_CLOSE PARENTHESIS_OPEN PARENTHESIS_CLOSE
COMMA SEMICOLON PERIOD PERIOD_PERIOD PERIOD_PERIOD_PERIOD COLON DOLLAR FORWARD_ARROW UNDERSCORE
NEWLINE INDENT DEDENT
CONST_PI CONST_TAU CONST_INF CONST_NAN
VCS_CONFLICT_MARKER BACKTICK QUESTION_MARK
ERROR TK_EOF TK_MAX""".split()

T = {n: i for i, n in enumerate(NAMES)}

TEXT = {
    'LESS': '<', 'LESS_EQUAL': '<=', 'GREATER': '>', 'GREATER_EQUAL': '>=',
    'EQUAL_EQUAL': '==', 'BANG_EQUAL': '!=',
    'AND': 'and', 'OR': 'or', 'NOT': 'not',
    'AMPERSAND_AMPERSAND': '&&', 'PIPE_PIPE': '||', 'BANG': '!',
    'AMPERSAND': '&', 'PIPE': '|', 'TILDE': '~', 'CARET': '^',
    'LESS_LESS': '<<', 'GREATER_GREATER': '>>',
    'PLUS': '+', 'MINUS': '-', 'STAR': '*', 'STAR_STAR': '**', 'SLASH': '/', 'PERCENT': '%',
    'EQUAL': '=', 'PLUS_EQUAL': '+=', 'MINUS_EQUAL': '-=', 'STAR_EQUAL': '*=',
    'STAR_STAR_EQUAL': '**=', 'SLASH_EQUAL': '/=', 'PERCENT_EQUAL': '%=',
    'LESS_LESS_EQUAL': '<<=', 'GREATER_GREATER_EQUAL': '>>=',
    'AMPERSAND_EQUAL': '&=', 'PIPE_EQUAL': '|=', 'CARET_EQUAL': '^=',
    'IF': 'if', 'ELIF': 'elif', 'ELSE': 'else', 'FOR': 'for', 'WHILE': 'while',
    'BREAK': 'break', 'CONTINUE': 'continue', 'PASS': 'pass', 'RETURN': 'return',
    'MATCH': 'match', 'WHEN': 'when',
    'AS': 'as', 'ASSERT': 'assert', 'AWAIT': 'await', 'BREAKPOINT': 'breakpoint',
    'CLASS': 'class', 'CLASS_NAME': 'class_name', 'CONST': 'const', 'ENUM': 'enum',
    'EXTENDS': 'extends', 'FUNC': 'func', 'IN': 'in', 'IS': 'is',
    'NAMESPACE': 'namespace', 'PRELOAD': 'preload', 'SELF': 'self', 'SIGNAL': 'signal',
    'STATIC': 'static', 'SUPER': 'super', 'TRAIT': 'trait', 'VAR': 'var',
    'VOID': 'void', 'YIELD': 'yield',
    'BRACKET_OPEN': '[', 'BRACKET_CLOSE': ']', 'BRACE_OPEN': '{', 'BRACE_CLOSE': '}',
    'PARENTHESIS_OPEN': '(', 'PARENTHESIS_CLOSE': ')',
    'COMMA': ',', 'SEMICOLON': ';', 'PERIOD': '.', 'PERIOD_PERIOD': '..',
    'PERIOD_PERIOD_PERIOD': '...', 'COLON': ':', 'DOLLAR': '$',
    'FORWARD_ARROW': '->', 'UNDERSCORE': '_',
    'CONST_PI': 'PI', 'CONST_TAU': 'TAU', 'CONST_INF': 'INF', 'CONST_NAN': 'NAN',
    'BACKTICK': '`', 'QUESTION_MARK': '?',
}
